### ISSUE TITLE
can't get example fastqs

### ISSUE THREAD

**Issue by robertbjornson** [voutcn/megahit#112]
I am not able to download the example fastq files using wget.

wget http://www.bio8.cs.hku.hk/dataset/MEGAHIT/SRR341725_1.fastq.gz
wget http://www.bio8.cs.hku.hk/dataset/MEGAHIT/SRR341725_2.fastq.gz

(I get permission denied).  

Rob Bjornson

**Comment by voutcn** [comment]
fixed.

**Comment by robertbjornson** [comment]
Sorry, it still fails:

[rdb9@farnam2 megahit_sample_data]$ wget http://www.bio8.cs.hku.hk/dataset/MEGAHIT/SRR341725_1.fastq.gz
--2017-02-06 09:27:46--  http://www.bio8.cs.hku.hk/dataset/MEGAHIT/SRR341725_1.fastq.gz
Resolving www.bio8.cs.hku.hk (www.bio8.cs.hku.hk)... 147.8.179.16
Connecting to www.bio8.cs.hku.hk (www.bio8.cs.hku.hk)|147.8.179.16|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-02-06 09:27:47 ERROR 403: Forbidden.

Rob

**Comment by voutcn** [comment]
My apologies. To make it clear, I did not recover our server. I revised the tutorial to use another link instead.
`wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR341/SRR341725/SRR341725_[12].fastq.gz`

**Comment by robertbjornson** [comment]
Hi Dinghua,

That's working, thanks very much!

Rob
